Vineria/urls.py
from django.conf.urls import include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    #url(r'^products/', include('products.urls')),
    url(r'^', include('products.urls')),
    url(r'^', include('proveedores.urls')),
    url(r'^', include('users.urls')),
	url(r'^', include('cajadiaria.urls')),
]

products/urls.py
from django.conf.urls import patterns, url
from products import views

urlpatterns = [
  url(r'^products/$', views.product_list, name='product_list'),
  url(r'^new$', views.product_create, name='product_new'),
  url(r'^$', views.home, name='home'),
  url(r'^ventas$', views.ventas, name='ventas'),
  url(r'^edit/(?P<pk>\d+)$', views.product_update, name='product_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.product_delete, name='product_delete'),
  url(r'^login/$', views.login, name='login'),
  url(r'^login_view/$', views.login_view, name='login_view'),
  url(r'^logout_view/$', views.logout_view, name='logout_view'),
  url(r'^datos_prod/$', views.DatosProductos.as_view(), name='datos_prod'),
  url(r'^realizarventa/$', views.realizarventa, name='realizarventa'),
  url(r'^ventarealizada/$', views.ventarealizada, name='ventarealizada'),
]

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = [
  url(r'^users/$', views.index, name='index'),
  url(r'^registrar_usuario/$', views.user_create, name='user_create'),
  url(r'^borrar_usuario/(?P<pk>\d+)$', views.user_delete, name='user_delete'),
  url(r'^listar_usuarios/$', views.user_list, name='user_list'),
]

products/models.py
from django.db import models
from django.core.urlresolvers import reverse
from proveedores.models import Proveedor

class Product(models.Model):
    name = models.CharField(max_length=50, default="N/A")
    productType = models.CharField(max_length=30, default="N/A")
    brand = models.CharField(max_length=30, default="N/A")
    price = models.FloatField(default='00.00')
    precio_lista = models.FloatField(default='00.00')
    productStock = models.IntegerField(default='0')
    description = models.CharField(max_length=200, default="N/A")
    year = models.IntegerField(default='0000')
    variety = models.CharField(max_length=30, default="N/A")
    origin = models.CharField(max_length=30, default="N/A")
    maker = models.CharField(max_length=50, default="N/A")
    size = models.FloatField(default='00.00')
    codigo = models.CharField(primary_key=True,max_length=30, default="")

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_edit', kwargs={'pk': self.pk})

class Venta(models.Model):
    products =  models.ManyToManyField(Product, through='VentaProducto')
    fecha = models.DateTimeField(auto_now=True)
    estado = models.TextField(max_length=2, default="BO")
    total = models.FloatField(default='00.00')
    descuento = models.FloatField(default='0')

class VentaProducto(models.Model):
    venta = models.ForeignKey(Venta)
    product = models.ForeignKey(Product)
    cant = models.IntegerField(default='0000')
    precio = models.FloatField(default='00.00')

products/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib import auth
from products.models import Product
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from products.models import Product,Venta,VentaProducto,Proveedor
from django.views.generic.base import TemplateView
from django.core import serializers
from django.http import HttpResponse
from django.http import Http404
from django.db.models import Sum,F
from django.db.models.fields import FloatField
import json

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ['codigo', 'name', 'productType', 'brand', 'price', 'precio_lista', 'productStock', 'description', 'year', 'variety', 'origin', 'maker', 'size']

def home(request, template_name='products/home.html'):
    if request.user.is_authenticated():
        return render(request, template_name, {})
    else:
        return render(request, 'products/login.html', {})

def ventas(request, template_name='products/vineriaVentas.html'):
    if request.user.is_authenticated():
        id_venta = Venta.objects.filter(estado='BO').values('id')
        if id_venta:
            VentaProducto.objects.filter(venta_id =int(id_venta[0].get('id'))).delete()
            Venta.objects.filter(estado='BO').delete()
        venta = Venta()
        venta.save()
        return render(request, template_name, {})
    else:
        return render(request, 'products/login.html', {})

def product_list(request, template_name='products/product_list.html'):
    if request.user.is_authenticated():
        products = Product.objects.all()
        data = {}
        data['object_list'] = products
        return render(request, template_name, data)
    else:
        return render(request, 'products/login.html', {})

def product_create(request, template_name='products/product_form.html'):
    if request.user.is_authenticated():
        form = ProductForm(request.POST or None)
        if form.is_valid():
            scannedCode = form.data["codigo"]
            matchingProducts = Product.objects.filter(codigo=scannedCode)
            if matchingProducts.count()>0:
                #no escanea y redirije a product_form
                #de nuevo con el parámetro inválido
                return render(request, 'product_form.html', {})
            else:
                form.save()
                return redirect('product_list')
        return render(request, template_name, {'form':form})
    else:
        return render(request, 'products/login.html', {})

def product_update(request, pk, template_name='products/product_edit.html'):
    if request.user.is_authenticated():
        product = get_object_or_404(Product, pk=pk)
        form = ProductForm(request.POST or None, instance=product)
        if form.is_valid():
            form.save()
            return redirect('product_list')
        return render(request, template_name, {'form':form})
    else:
        return render(request, 'products/login.html', {})

def product_delete(request, pk, template_name='products/product_confirm_delete.html'):
    if request.user.is_authenticated():
        product = get_object_or_404(Product, codigo=pk)
        if request.method=='POST':
            product.delete()
            return redirect('product_list')
        return render(request, template_name, {'product':product})
    else:
        return render(request, 'products/login.html', {})

def login(request, template_name='products/login.html'):
    return render(request, template_name, {})

@csrf_exempt
def login_view(request):
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
    if user is not None and user.is_active:
        # Correct password, and the user is marked "active"
        auth.login(request, user)
        context = {}
        #request_context = RequestContext(request)
        # Redirect to a success page.
        #return render_to_response('Cervezas.html',context,request_context=request_context)
        return render(request,'products/home.html',{})
    else:
        # Show an error page
        return render(request,'products/login.html',{})

def logout_view(request):
    auth.logout(request)
    return render(request,'products/login.html',{})

class DatosProductos(TemplateView):

    def get(self, request, *args, **kwargs):
        id_venta = Venta.objects.filter(estado='BO').values('id')
        cantidad = request.GET['cantidad']
        id_prod = request.GET['pk'];
        try:
            products = Product.objects.get(codigo=id_prod)
            prodexistente= VentaProducto.objects.filter(product_id=id_prod,venta_id=int(id_venta[0].get('id')))
            if prodexistente.count()>0:
                pe = prodexistente[0]
                c = pe.cant
                pe.cant = (c + int(cantidad))
                pe.save()
            else:
                ventaprod = VentaProducto()
                ventaprod.venta_id = int(id_venta[0].get('id'))
                ventaprod.product_id=id_prod
                ventaprod.precio = products.price
                ventaprod.cant=cantidad
                ventaprod.save()
        except Product.DoesNotExist:
            raise Http404("")
        data = serializers.serialize('json',[products])
        return HttpResponse(data, content_type ="application/json")

def realizarventa(request):
    descpesos = request.GET['descpesos']
    descporc = request.GET['descporc']
    id_venta = Venta.objects.filter(estado='BO').values('id')
    venta = Venta(id_venta[0].get('id'))
    sumventas = VentaProducto.objects.filter(venta_id=id_venta[0].get('id')).aggregate(total=Sum(F('precio')*F('cant'), output_field=FloatField()))
    venta.total = sumventas.get('total')
    if (descporc != ''):
       venta.descuento = (venta.total*float(descporc))/100
    if (descpesos != ''):
        venta.descuento = descpesos
    venta.estado = 'CO'
    venta.save()
    response = {}
    return HttpResponse({},'')

def ventarealizada(request):
    return render(request,'products/ventarealizada.html',{})

products/templates/products/AcercaDe.html
<html>
{% include "products/header.html" %}
<body>
<div class="modal hide fade">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Modal header</h3>
  </div>
  <div class="modal-body">
    <p>One fine body…</p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn">Close</a>
    <a href="#" class="btn btn-primary">Save changes</a>
  </div>
</div>
<body>
</html>

products/templates/products/header.html
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
  <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
  <link href="http://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css" rel="stylesheet" type="text/css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
</head>
<body>
  <div style="padding:2px ; background-color:rgba(76,12,12,0.77)">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-9 text-left">
          <div class="btn-group btn-group">
            <a href="{% url "home" %}" class="btn btn-danger" title="Home" style="font-size:140%;">
            <span class="glyphicon glyphicon-home"></span>
            </a>
          </div>
          <div class="btn-group btn-group">
            <a class="btn btn-danger dropdown-toggle" data-toggle="dropdown"> Archivo </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{% url "user_list" %}">Usuarios</a></li>
              <li><a href="#">Acerca de...</a></li>
            </ul>
          </div>
          <div class="btn-group btn-group">
            <a class="btn btn-danger" id="abrircaja"></a>
          </div>
          <div class="btn-group btn-group">
            <a class="btn btn-danger dropdown-toggle" data-toggle="dropdown"> Productos </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{% url "product_new" %}">Nuevo Producto</a></li>
              <li><a href="{% url "product_list" %}">Ver Productos</a></li>
            </ul>
          </div>
          <div class="btn-group btn-group">
            <a class="btn btn-danger dropdown-toggle" data-toggle="dropdown"> Ventas </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{% url "ventas" %}">Nueva Venta</a></li>
              <li><a href="#">Ver Ventas</a></li>
            </ul>
          </div>
          <div class="btn-group btn-group">
            <a class="btn btn-danger dropdown-toggle" data-toggle="dropdown"> Estadisticas </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Productos Vendidos</a></li>
            </ul>
          </div>
          <div class="btn-group btn-group">
            <a class="btn btn-danger dropdown-toggle" data-toggle="dropdown"> Proveedores </a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="{% url "prov_create" %}">Nuevo Proveedor</a></li>
              <li><a href="{% url "prov_list" %}">Ver Proveedores</a></li>
            </ul>
          </div>
        </div>
        <div class="col-md-3 text-left">
          <div class="btn-group btn-group-lg" style="top:15;width:55%;text-align:right;">
            <a style="color: white; text-decoration: none;"> Bienvenido, {{ user.username }}.</a>
          </div>
          <div class="btn-group btn-group" style="float: right;">
            <a class="btn btn-danger dropdown-toggle" href="{% url 'logout_view' %}"> Cerrar Sesión </a>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
</body>

<script type="text/javascript">
  $(document).ready(function(){
    $.ajax({
          url: '{% url "cajaabierta" %}',
          type: 'get',
          success: function(data){
            $('#abrircaja').html("Cerrar Caja");
          },
          error: function(data){
            $('#abrircaja').html("Abrir Caja");
          },
    });
    $('#abrircaja').on("click", function(e){
      if ($(this).html() == "Abrir Caja"){
        var saldo = prompt("Valor inicial de caja", "");
        $.ajax({
          data: {'saldo':saldo},
          url: '{% url "abrircaja" %}',
          type: 'get',
          success: function(data){
            $('#abrircaja').html("Cerrar Caja");
          },
        });
      }
      else {
        $.ajax({
          data: {'saldo':saldo},
          url: '{% url "cerrarcaja" %}',
          type: 'get',
          success: function(data){
            alert("El valor de caja: " + data.balance)
            $('#abrircaja').html("Abrir Caja");
          },
        });
      }
    });
  });
</script>  

products/templates/products/home.html
<html>
{% include "products/header.html" %}
<body style="background-image: url('http://remedyhealthcare.net/wp-content/uploads/2012/04/wine.jpg') ; background-position: center center ; background-size: cover; ">
</body>
</html>

products/templates/products/login.html
<html>
  <head>
    <link href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="http://pingendo.github.io/pingendo-bootstrap/themes/default/bootstrap.css" rel="stylesheet" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  </head>
   <body style="background-image: url('http://static1.squarespace.com/static/52eaf09be4b0e18798df3911/t/53a8236ae4b0e026bea5cb5f/1403528070892/Wine+Bottle+Background.jpg?format=2500w');
    background-position: center center;background-size: cover;">
    <div class="section">
      <div class="container">
        <div class="row">
          <div class="col-md-5"></div>
          <div class="col-md-4" style="padding-top: 20%;">
            <form action="{% url 'login_view' %}" method="post" style="width:70%;">
              {% csrf_token %}
              <div class="form-group" >
                <label class="control-label" for="exampleInputEmail1">Usuario</label>
                <input class="form-control" id="username" name="username"
                placeholder="Usuario" type="text" style="border: 2px solid #A03737;">
              </div>
              <div class="form-group">
                <label class="control-label" for="exampleInputPassword1">Contraseña</label>
                <input class="form-control" id="password" name="password"
                placeholder="Password" type="password" style="border: 2px solid #A03737;">
              </div>
              <button type="submit" class="btn btn-danger">Entrar</button>
              <input type="hidden" name="next" value="{{ next|escape }}" />
            </form>
          </div>
          <div class="col-md-3"></div>
        </div>
      </div>
    </div>
  </body>
</html>

products/templates/products/product_confirm_delete.html
{% include "products/header.html" %}
<body>
  <div class="section text-center">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form method="post" class="form-horizontal" role="form"> {% csrf_token %}
            <label class="control-label">Eliminar "{{ product }}" ?</label>
          </br>
          </br>
          </br>
          <div class="form-group">
            <div class="col-sm-3"></div>
            <div class="col-sm-3">
              <button type="submit" class="btn btn-success">Confirmar</button>
            </div>
            <div class="col-sm-3">
              <a href="{% url "product_list" %}" class="btn btn-danger">
              <span class=""></span> Cancelar
              </a>
            </div>
            <div class="col-sm-3"></div>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

products/templates/products/product_edit.html
{% include "products/header.html" %}
<body>
  <div style="padding:5%" class="section text-center">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form method="post" class="form-horizontal" role="form"> {% csrf_token %}

            <!-- <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Código</label>
              </div>
              <div class="col-sm-4">
                {{form.codigo}}
              </div>
            </div> -->
            <div class="form-group" id="nombre">
              <div class="col-sm-6">
                <label class="control-label">Nombre</label>
              </div>
              <div class="col-sm-4">
                {{form.name}}
              </div>
            </div>
            <div class="form-group" id="tipo">
              <div class="col-sm-6">
                <label class="control-label">Tipo</label>
              </div>
              <div class="col-sm-4">
                {{form.productType}}
              </div>
            </div>
            <div class="form-group" id="marca">
              <div class="col-sm-6">
                <label class="control-label">Marca</label>
              </div>
              <div class="col-sm-4">
                {{form.brand}}
              </div>
            </div>
            <div class="form-group" id="descripcion">
              <div class="col-sm-6">
                <label class="control-label">Descripción</label>
              </div>
              <div class="col-sm-4">
                {{form.description}}
              </div>
            </div>
            <div class="form-group" id="variedad">
              <div class="col-sm-6">
                <label class="control-label">Variedad</label>
              </div>
              <div class="col-sm-4">
                {{form.variety}}
              </div>
            </div>
            <div class="form-group" id="origen">
              <div class="col-sm-6">
                <label class="control-label">Origen</label>
              </div>
              <div class="col-sm-4">
                {{form.origin}}
              </div>
            </div>
            <div class="form-group" id="fabricante">
              <div class="col-sm-6">
                <label class="control-label">Fabricante</label>
              </div>
              <div class="col-sm-4">
                {{form.maker}}
              </div>
            </div>
            <div class="form-group" id="talle">
              <div class="col-sm-6">
                <label class="control-label">Talle</label>
              </div>
              <div class="col-sm-4">
                {{form.talle}}
              </div>
            </div>
            <div class="form-group" id="precioVenta">
              <div class="col-sm-6">
                <label class="control-label">Precio de venta</label>
              </div>
              <div class="col-sm-4">
                {{form.price}}
              </div>
            </div>
            <div class="form-group" id="precioLista">
              <div class="col-sm-6">
                <label class="control-label">Precio de lista</label>
              </div>
              <div class="col-sm-4">
                {{form.precio_lista}}
              </div>
            </div>
            <div class="form-group" id="stock">
              <div class="col-sm-6">
                <label class="control-label">Stock</label>
              </div>
              <div class="col-sm-4">
                {{form.productStock}}
              </div>
            </div>
            <div class="form-group" id="año">
              <div class="col-sm-6">
                <label class="control-label">Año</label>
              </div>
              <div class="col-sm-4">
                {{form.year}}
              </div>
            </div>
            <div class="form-group" id="tamaño">
              <div class="col-sm-6">
                <label class="control-label">Tamaño</label>
              </div>
              <div class="col-sm-4">
                {{form.size}}
              </div>
            </div>

            </br>

            <div class="col-sm-6">
              <button type="submit" class="btn btn-success">Confirmar</button>
            </div>

              <div class="col-sm-4">
                <a href="{% url "product_list" %}" class="btn btn-danger">
                <span class=""></span> Cancelar
                </a>
              </div>
            </div>

          </form>
        </div>
      </div>
    </div>
  </div>
</body>

products/templates/products/product_form.html
{% include "products/header.html" %}
<body>
  <div style="padding:5%" class="section text-center">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <form id="productAddForm" method="post" class="form-horizontal" role="form"> {% csrf_token %}

            <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Nombre</label>
              </div>
              <div class="col-sm-4">
                {{form.name}}
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Tipo</label>
              </div>
              <div class="col-sm-4">
                {{form.productType}}
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Marca</label>
              </div>
              <div class="col-sm-4">
                {{form.brand}}
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Descripción</label>
              </div>
              <div class="col-sm-4">
                {{form.description}}
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Variedad</label>
              </div>
              <div class="col-sm-4">
                {{form.variety}}
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Origen</label>
              </div>
              <div class="col-sm-4">
                {{form.origin}}
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Fabricante</label>
              </div>
              <div class="col-sm-4">
                {{form.maker}}
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Precio</label>
              </div>
              <div class="col-sm-4">
                {{form.price}}
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Stock</label>
              </div>
              <div class="col-sm-4">
                {{form.productStock}}
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Año</label>
              </div>
              <div class="col-sm-4">
                {{form.year}}
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Tamaño</label>
              </div>
              <div class="col-sm-4">
                {{form.size}}
              </div>
            </div>
</br>
            <div class="form-group">
              <div class="col-sm-6">
                <label class="control-label">Código</label>
              </div>
              <div id="codeInput" class="col-sm-4">
                {{form.codigo}}
              </div>
            </div>
            </br>


            <div class="form-group">
              <div class="col-sm-6">
                <a href="#" id="codeScanner" class="btn btn-success">
                <span class=""></span> Escanear Código
                </a>
              </div>

              <div class="col-sm-4">
                <a href="{% url "product_list" %}" class="btn btn-danger">
                <span class=""></span> Cancelar
                </a>
              </div>
            </div>

            <!-- <div class="col-sm-6" style="display:none;">
              <button type="submit" class="btn btn-success">Confirmar</button>
            </div> -->

          </form>
        </div>
      </div>
    </div>
  </div>
<script type="text/javascript">
  $(document).ready(function(){

    function isInt(value) {
      var x = parseFloat(value);
      return !isNaN(value) && (x | 0) === x;
    }

    var alertShown = false;
    var codeScanner = $("#codeScanner");
    var codeInput = $("#id_codigo");
    codeInput.prop("readonly", true);
    var code = codeInput.val();

    if (code != "" && code != null && code != " ") {
      alert("El código ingresado ya existe! Ingrese uno diferente.");
      if (!alertShown) {
        alertShown = true;
        //codeScanner.click();
      }
    }

    codeScanner.on("click", function(e){
      e.preventDefault();
      var code = prompt("Escanee el código de barras del producto o ingrese manualmente el código", "Esperando...");
      if (isInt(code)) {
        codeInput.val(code);
        $("#productAddForm").submit();
      }
      else{
        alert("El valor ingresado no es un código válido. Vuelva a ingresarlo.");
        //codeScanner.click();
      }
    });
  });
</script>
</body>

products/templates/products/product_list.html
{% include "products/header.html" %}
<body>
    <style>
    .table td {
     text-align: center;
     }
     .table th {
      text-align: center;
      }
    </style>
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h1 style="text-align:center;">Productos</h1>
          </br>
          </br>
          <div>
          <span style="font-size: 18px;padding-right:1%;">Filtrar</span>
          <input style="border-style:solid;text-align:center;" id="searchInput" text="Buscar...">
        </div>
        </br>
        </br>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Código</th>
                <th>Nombre</th>
                <th>Tipo</th>
                <th>Marca</th>
                <th>Precio</th>
                <th>Stock</th>
                <th>Descripción</th>
                <th>Año</th>
                <th>Variedad</th>
                <th>Origen</th>
                <th>Fabricante</th>
                <th>Tamaño</th>
              </tr>
            </thead>
            <tbody id="tableToFilter">
              {% for product in object_list %}
              <tr>
                  <td>{{ product.codigo }}</td>
                  <td>{{ product.name }}</td>
                  <td>{{ product.productType }}</td>
                  <td>{{ product.brand }}</td>
                  <td>${{ product.price }}</td>
                  <td>{{ product.productStock }}</td>
                  <td>{{ product.description }}</td>
                  <td>{{ product.year }}</td>
                  <td>{{ product.variety }}</td>
                  <td>{{ product.origin }}</td>
                  <td>{{ product.maker }}</td>
                  <td>{{ product.size }} cc</td>
                  <td>
                    <a href="{% url "product_edit" product.codigo %}" class="btn btn-info" title="Editar">
                    <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                  </td>
                  <td>
                    <a href="{% url "product_delete" product.codigo %}" class="btn btn-danger" title="Borrar">
                    <span class="glyphicon glyphicon-trash"></span>
                    </a>
                  </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
          <a href="{% url "product_new" %}" class="btn btn-success btn-lg">
          <span class="glyphicon glyphicon-plus"></span> Nuevo Producto
          </a>
        </div>
      </div>
    </div>
  </div>
<script type="text/javascript">
$(document).ready(function(){

  var searchInputSelector = $("#searchInput");
  var tableToFilterSelector = $("#tableToFilter");

  searchInputSelector.keyup(function () {
    //split the current value of searchInput
    var data = this.value.toUpperCase().split(" ");
    //create a jquery object of the rows
    var jo = tableToFilterSelector.find("tr");
    if (this.value == "") {
      jo.show();
      return;
    }
    //hide all the rows
    jo.hide();

    //Recusively filter the jquery object to get results.
    jo.filter(function (i, v) {
      var $t = $(this);
      for (var d = 0; d < data.length; ++d) {
        if ($t.text().toUpperCase().indexOf(data[d]) > -1) {
          return true;
        }
      }
      return false;
    })
    //show the rows that match.
    .show();
  }).focus(function () {
    this.value = "";
    $(this).css({
      "color": "black"
    });
    $(this).unbind('focus');
  }).css({
    "color": "#C0C0C0"
  });
});
</script>
</body>

products/templates/products/ventarealizada.html
<html>
{% include "products/header.html" %}
<h1 style="text-align: center;">Venta realizada con éxito</h1>

<script>
setTimeout(function() {
  window.location.href = "{% url 'ventas' %}";
}, 800);
</script>